- src/Routes/HomePage/index.js
> Updates for RHODA page service preview

- src/Routes/HomePage/index.js
* Updates for RHODA page service preview
[Jira Ref RHCLOUD-17582]
* Fix linter errors
> [stable] Updates for RHODA page service preview (#5)

- src/Routes/HomePage/index.js
* Updates for RHODA page service preview
[Jira Ref RHCLOUD-17582]
* Fix linter errors
> [prod-beta] Updates for RHODA page service preview (#5)

- src/Routes/HomePage/index.js
* Updates for RHODA page service preview
[Jira Ref RHCLOUD-17582]
* Fix linter errors
> [prod-stable] Updates for RHODA page service preview (#5)

- src/Routes/HomePage/index.js
> RHODA service preview update youtube url's

- README.md
- config/dev.webpack.config.js
- package-lock.json
- package.json
> Update FEC to fix local deployment

- src/Routes/HomePage/index.js
Hi all, attempting our team's first commit so I'm also figuring out the process. PTAL, thanks!
> RHODA 0.2.0 verbiage updates

- src/Routes/HomePage/index.js
PR GOAL: INTRODUCE TO STAGING FOR TESTING/VALIDATION - IS 'MASTER' CORRECT TARGET?
Add Segment/Amplitude events for each user call to action opening a new external link from our site. There are three such buttons currently in the app (see screenshot) identified for first implementation.
> DBAAS-988: adding 3 event trackers to RHODA UX buttons

- src/Routes/HomePage/index.js
Reverts RedHatInsights/dbaas-ui#18
> Revert "DBAAS-988: adding 3 event trackers to RHODA UX buttons"

- .travis/custom_release.sh
- src/Routes/HomePage/index.js
Events captured in staging-beta Segment live debugger flow:
> DBAAS-988: adding trackers to 3 RHODA buttons for user journey [prod-beta]

- .travis/custom_release.sh
- src/Routes/HomePage/index.js
Events captured in staging-beta Segment live debugger flow:
> DBAAS-988: adding trackers to 3 RHODA buttons for user journey [master-stable]

- .travis/custom_release.sh
- src/Routes/HomePage/index.js
Events captured in staging-beta Segment live debugger flow:
> DBAAS-988: adding trackers to 3 RHODA buttons for user journey [prod-stable]

- src/Routes/HomePage/consts.js
- src/Routes/HomePage/index.js
Jira: [https://issues.redhat.com/browse/DBAAS-1218](https://issues.redhat.com/browse/DBAAS-1218)
Jira: [https://issues.redhat.com/browse/DBAAS-1215](https://issues.redhat.com/browse/DBAAS-1215)
> DBAAS-1218:Fixed the display for ROSA cluster and added scroll bar for cluster selection dropdown

- src/Routes/HomePage/index.js
Updated the "Join waitlist" button to "Join waiting list".
> Updated the button text

- config/dev.webpack.config.js
- config/prod.webpack.config.js
- src/Routes/HomePage/index.js
If you have configured your `/etc/hosts` file in the past you can skip this step.
- Open a terminal and execute the following script https://github.com/RedHatInsights/insights-proxy/blob/master/scripts/patch-etc-hosts.sh
- Clone this repository and checkout this PR
- Install NPM dependencies
```
npm ci
```
- Start the UI 
```
npm run start
```
Open your browser at https://stage.foo.redhat.com:1337/application-services/trusted-content
We currently have 4 branches:
- master => I have to figure out
- master-stable => https://console.stage.redhat.com/application-services/trusted-content
- prod-beta => https://console.redhat.com/beta/application-services/trusted-content
- prod-stable => https://console.redhat.com/application-services/trusted-content
> Add launch button to home page

- config/dev.webpack.config.js
- config/prod.webpack.config.js
- src/Routes/HomePage/index.js
cherry pick https://github.com/RedHatInsights/dbaas-ui/pull/48
> Add launch button to home page: master-stable

- src/Routes/HomePage/index.js
https://issues.redhat.com/browse/TC-616
> fix: Fix typo in home page

- package-lock.json
- package.json
- src/AppEntry.js
jira: https://issues.redhat.com/browse/RHCLOUD-29121
> fix: update router basename based on runtime environment

- src/Routes/HomePage/index.tsx
Cherry-pick https://github.com/RedHatInsights/dbaas-ui/pull/65
> [TC-703]: Remove "Launch Trusted Content" button (#65)

- src/Routes/HomePage/index.tsx
Cherry-pick https://github.com/RedHatInsights/dbaas-ui/pull/66
> [TC-703]: Remove "Launch Trusted Content" button (#65) (#66)

- src/Routes/HomePage/index.tsx
Cherry-pick https://github.com/RedHatInsights/dbaas-ui/pull/67
> [TC-703]: Remove "Launch Trusted Content" button (#65) (#66) (#67)

- src/Routes/HomePage/index.tsx
This is related to https://issues.redhat.com/browse/TC-703 meanwhile we want to restore access to the preview from the staging area.
> [TC-703] - Restore launch button

- src/Routes/HomePage/index.tsx
(cherry picked from commit 330d7bb77428ca97c558c54d6fa37129eec7def2)
> [TC-703] - Restore launch button (#69)

- src/Routes/HomePage/index.tsx
- src/common/analytics.ts
https://issues.redhat.com/browse/TC-796
> [TC-796] - Change RHTPA welcome page

- src/Routes/HomePage/consts.ts
https://github.com/RedHatInsights/dbaas-ui/pull/76
> Fix staging rhtpa url master stable

- src/App.tsx
- src/Routes/HomePage/consts.ts
- src/Routes/HomePage/index.tsx
- src/common/analytics.ts
* Resolve conflicts
* RHTPA: Change staging RHTPA url (#76) (#77)
* Change staging RHTPA url
* Fix urls
> RHTPA: service preview release

- src/Routes/HomePage/home-page.scss
- src/Routes/HomePage/index.tsx
> THTPA: home page UX enhancements

- src/Routes/HomePage/home-page.scss
- src/Routes/HomePage/index.tsx
* Save work from alessandro
* Set download button colors
> THTPA: home page UX enhancements (#80)

- src/Routes/HomePage/home-page.scss
- src/Routes/HomePage/index.tsx
* Save work from alessandro
* Set download button colors
> THTPA: home page UX enhancements (#80) (#81)

- src/Routes/HomePage/home-page.scss
- src/Routes/HomePage/index.tsx
* Save work from alessandro
* Set download button colors
> THTPA: home page UX enhancements (#80) (#81) (#82)

- src/hooks/misc.ts
> updating rhtas docs link for prod-stable

- src/hooks/misc.ts
> updating rhtas docs link for prod-beta

- src/hooks/misc.ts
> updating rhtas docs link for master-stable

- src/hooks/misc.ts
/hold
waiting for @agunn303 to confirm this link
> bump rhtas docs version for GA release

- src/Routes/HomePage/index.tsx
https://issues.redhat.com/browse/TC-1170
> [TC-1170] - RHTPA - Update home description text

- src/Routes/HomePage/consts.ts
- src/Routes/HomePage/index.tsx
- src/common/analytics.ts
https://issues.redhat.com/browse/TC-1170
Cherry-picks of:
- https://github.com/RedHatInsights/dbaas-ui/commit/402fda677daa57c344cf01267a334811faf47a12
- https://github.com/RedHatInsights/dbaas-ui/commit/e67bb67c3fe4c993b8ed699cd9582e900b62c7b6
> [TC-1170] - master-stable - Add Install on Premise button to console page 

- src/Routes/HomePage/consts.ts
- src/Routes/HomePage/index.tsx
- src/common/analytics.ts
https://issues.redhat.com/browse/TC-1170
Cherry-picks of:
- https://github.com/RedHatInsights/dbaas-ui/commit/402fda677daa57c344cf01267a334811faf47a12
- https://github.com/RedHatInsights/dbaas-ui/commit/e67bb67c3fe4c993b8ed699cd9582e900b62c7b6
> [TC-1170] - prod-beta  - Add Install on Premise button to console page

- src/Routes/HomePage/consts.ts
- src/Routes/HomePage/index.tsx
- src/common/analytics.ts
https://issues.redhat.com/browse/TC-1170
Cherry-picks of:
- https://github.com/RedHatInsights/dbaas-ui/commit/402fda677daa57c344cf01267a334811faf47a12
- https://github.com/RedHatInsights/dbaas-ui/commit/e67bb67c3fe4c993b8ed699cd9582e900b62c7b6
> [TC-1170] - prod-stable - Add Install on Premise button to console page

- src/Routes/HomePage/consts.ts
- src/Routes/HomePage/index.tsx
https://issues.redhat.com/browse/TC-1264
> [TC-1264] - RHTPA- GA: Update Home page
